const ASCII_TABLE = [
  { name: 'NUL', value: 0, remark: 'Null character' },
  { name: 'SOH', value: 1, remark: 'Start of Heading' },
  { name: 'STX', value: 2, remark: 'Start of Text' },
  { name: 'ETX', value: 3, remark: 'End of Text' },
  { name: 'EOT', value: 4, remark: 'End of Transmission' },
  { name: 'ENQ', value: 5, remark: 'Enquiry' },
  { name: 'ACK', value: 6, remark: 'Acknowledge' },
  { name: 'BEL', value: 7, remark: 'Bell, Alert' },
  { name: 'BS', value: 8, remark: 'Backspace' },
  { name: 'HT', value: 9, remark: 'Horizontal Tab' },
  { name: 'LF', value: 10, remark: 'Line Feed' },
  { name: 'VT', value: 11, remark: 'Vertical Tabulation' },
  { name: 'FF', value: 12, remark: 'Form Feed' },
  { name: 'CR', value: 13, remark: 'Carriage Return' },
  { name: 'SO', value: 14, remark: 'Shift Out' },
  { name: 'SI', value: 15, remark: 'Shift In' },
  { name: 'DLE', value: 16, remark: 'Data Link Escape' },
  { name: 'DC1', value: 17, remark: 'Device Control One (XON)' },
  { name: 'DC2', value: 18, remark: 'Device Control Two' },
  { name: 'DC3', value: 19, remark: 'Device Control Three (XOFF)' },
  { name: 'DC4', value: 20, remark: 'Device Control Four' },
  { name: 'NAK', value: 21, remark: 'Negative Acknowledge' },
  { name: 'SYN', value: 22, remark: 'Synchronous Idle' },
  { name: 'ETB', value: 23, remark: 'End of Transmission Block' },
  { name: 'CAN', value: 24, remark: 'Cancel' },
  { name: 'EM', value: 25, remark: 'End of medium' },
  { name: 'SUB', value: 26, remark: 'Substitute' },
  { name: 'ESC', value: 27, remark: 'Escape' },
  { name: 'FS', value: 28, remark: 'File Separator' },
  { name: 'GS', value: 29, remark: 'Group Separator' },
  { name: 'RS', value: 30, remark: 'Record Separator' },
  { name: 'US', value: 31, remark: 'Unit Separator' },
  { name: 'SP', value: 32, remark: 'Space' },
  { name: 'DEL', value: 127, remark: 'Delete' },
] 
