const CURRENCIES_LIST = [
  { key: 'AED', flag: 'ae', name: 'UAE Dirham', },
  { key: 'AFN', flag: 'af', name: 'Afghani', },
  { key: 'ALL', flag: 'al', name: 'Lek', },
  { key: 'AMD', flag: 'am', name: 'Armenian Dram', },
  { key: 'AOA', flag: 'ao', name: 'Kwanza', },
  { key: 'ARS', flag: 'ar', name: 'Argentine Peso', },
  { key: 'AUD', flag: 'au', name: 'Australian Dollar', },
  { key: 'AWG', flag: 'aw', name: 'Aruban Florin', },
  { key: 'AZN', flag: 'az', name: 'Azerbaijanian Manat', },
  { key: 'BAM', flag: 'ba', name: 'Convertible Mark', },
  { key: 'BBD', flag: 'bb', name: 'Barbados Dollar', },
  { key: 'BDT', flag: 'bd', name: 'Taka', },
  { key: 'BHD', flag: 'bh', name: 'Bahraini Dinar', },
  { key: 'BIF', flag: 'bi', name: 'Burundi Franc', },
  { key: 'BMD', flag: 'bm', name: 'Bermudian Dollar', },
  { key: 'BND', flag: 'bn', name: 'Brunei Dollar', },
  { key: 'BOB', flag: 'bo', name: 'Boliviano', },
  { key: 'BRL', flag: 'br', name: 'Brazilian Real', },
  { key: 'BSD', flag: 'bs', name: 'Bahamian Dollar', },
  { key: 'BTN', flag: 'bt', name: 'Ngultrum', },
  { key: 'BWP', flag: 'bw', name: 'Pula', },
  { key: 'BYN', flag: 'by', name: 'Belarussian Ruble', },
  { key: 'BZD', flag: 'bz', name: 'Belize Dollar', },
  { key: 'CAD', flag: 'ca', name: 'Canadian Dollar', },
  { key: 'CDF', flag: 'cd', name: 'Congolese Franc', },
  { key: 'CHF', flag: 'ch', name: 'Swiss Franc', },
  { key: 'CLF', flag: 'cl', name: 'Unidad de Fomento', },
  { key: 'CLP', flag: 'cl', name: 'Chilean Peso', },
  { key: 'CNY', flag: 'cn', name: 'Yuan Renminbi', },
  { key: 'COP', flag: 'co', name: 'Colombian Peso', },
  { key: 'CRC', flag: 'cr', name: 'Costa Rican Colon', },
  { key: 'CUC', flag: 'cu', name: 'Peso Convertible', },
  { key: 'CUP', flag: 'cu', name: 'Cuban Peso', },
  { key: 'CVE', flag: 'cv', name: 'Cabo Verde Escudo', },
  { key: 'CZK', flag: 'cz', name: 'Czech Koruna', },
  { key: 'DJF', flag: 'dj', name: 'Djibouti Franc', },
  { key: 'DKK', flag: 'dk', name: 'Danish Krone', },
  { key: 'DOP', flag: 'do', name: 'Dominican Peso', },
  { key: 'DZD', flag: 'dz', name: 'Algerian Dinar', },
  { key: 'EGP', flag: 'eg', name: 'Egyptian Pound', },
  { key: 'ERN', flag: 'er', name: 'Nakfa', },
  { key: 'ETB', flag: 'et', name: 'Ethiopian Birr', },
  { key: 'EUR', flag: 'eu', name: 'Euro', },
  { key: 'FJD', flag: 'fj', name: 'Fiji Dollar', },
  { key: 'FKP', flag: 'fk', name: 'Falkland Islands Pound', },
  { key: 'GBP', flag: 'gb', name: 'Pound Sterling', },
  { key: 'GEL', flag: 'ge', name: 'Lari', },
  { key: 'GHS', flag: 'gh', name: 'Ghana Cedi', },
  { key: 'GIP', flag: 'gi', name: 'Gibraltar Pound', },
  { key: 'GMD', flag: 'gm', name: 'Dalasi', },
  { key: 'GNF', flag: 'gn', name: 'Guinea Franc', },
  { key: 'GTQ', flag: 'gt', name: 'Quetzal', },
  { key: 'GYD', flag: 'gy', name: 'Guyana Dollar', },
  { key: 'HKD', flag: 'hk', name: 'Hong Kong Dollar', },
  { key: 'HNL', flag: 'hn', name: 'Lempira', },
  { key: 'HTG', flag: 'ht', name: 'Gourde', },
  { key: 'HUF', flag: 'hu', name: 'Forint', },
  { key: 'IDR', flag: 'id', name: 'Rupiah', },
  { key: 'ILS', flag: 'il', name: 'New Israeli Sheqel', },
  { key: 'INR', flag: 'in', name: 'Indian Rupee', },
  { key: 'IQD', flag: 'iq', name: 'Iraqi Dinar', },
  { key: 'IRR', flag: 'ir', name: 'Iranian Rial', },
  { key: 'ISK', flag: 'is', name: 'Iceland Krona', },
  { key: 'JMD', flag: 'jm', name: 'Jamaican Dollar', },
  { key: 'JOD', flag: 'jo', name: 'Jordanian Dinar', },
  { key: 'JPY', flag: 'jp', name: 'Japanese Yen', },
  { key: 'KES', flag: 'ke', name: 'Kenyan Shilling', },
  { key: 'KGS', flag: 'kg', name: 'Som', },
  { key: 'KHR', flag: 'kh', name: 'Riel', },
  { key: 'KMF', flag: 'km', name: 'Comoro Franc', },
  { key: 'KPW', flag: 'kp', name: 'North Korean Won', },
  { key: 'KRW', flag: 'kr', name: 'South Korean Won', },
  { key: 'KWD', flag: 'kw', name: 'Kuwaiti Dinar', },
  { key: 'KYD', flag: 'ky', name: 'Cayman Islands Dollar', },
  { key: 'KZT', flag: 'kz', name: 'Tenge', },
  { key: 'LAK', flag: 'la', name: 'Kip', },
  { key: 'LBP', flag: 'lb', name: 'Lebanese Pound', },
  { key: 'LKR', flag: 'lk', name: 'Sri Lanka Rupee', },
  { key: 'LRD', flag: 'lr', name: 'Liberian Dollar', },
  { key: 'LSL', flag: 'ls', name: 'Loti', },
  { key: 'LYD', flag: 'ly', name: 'Libyan Dinar', },
  { key: 'MAD', flag: 'ma', name: 'Moroccan Dirham', },
  { key: 'MDL', flag: 'md', name: 'Moldovan Leu', },
  { key: 'MGA', flag: 'mg', name: 'Malagasy Ariary', },
  { key: 'MKD', flag: 'mk', name: 'Denar', },
  { key: 'MMK', flag: 'mm', name: 'Kyat', },
  { key: 'MNT', flag: 'mn', name: 'Tugrik', },
  { key: 'MOP', flag: 'mo', name: 'Pataca', },
  { key: 'MRU', flag: 'mr', name: 'Ouguiya', },
  { key: 'MUR', flag: 'mu', name: 'Mauritius Rupee', },
  { key: 'MVR', flag: 'mv', name: 'Rufiyaa', },
  { key: 'MWK', flag: 'mw', name: 'Kwacha', },
  { key: 'MXN', flag: 'mx', name: 'Mexican Peso', },
  { key: 'MYR', flag: 'my', name: 'Malaysian Ringgit', },
  { key: 'MZN', flag: 'mz', name: 'Mozambique Metical', },
  { key: 'NAD', flag: 'na', name: 'Namibia Dollar', },
  { key: 'NGN', flag: 'ng', name: 'Naira', },
  { key: 'NIO', flag: 'ni', name: 'Cordoba Oro', },
  { key: 'NOK', flag: 'no', name: 'Norwegian Krone', },
  { key: 'NPR', flag: 'np', name: 'Nepalese Rupee', },
  { key: 'NZD', flag: 'nz', name: 'New Zealand Dollar', },
  { key: 'OMR', flag: 'om', name: 'Rial Omani', },
  { key: 'PAB', flag: 'pa', name: 'Balboa', },
  { key: 'PEN', flag: 'pe', name: 'Nuevo Sol', },
  { key: 'PGK', flag: 'pg', name: 'Kina', },
  { key: 'PHP', flag: 'ph', name: 'Philippine Peso', },
  { key: 'PKR', flag: 'pk', name: 'Pakistan Rupee', },
  { key: 'PLN', flag: 'pl', name: 'Zloty', },
  { key: 'PYG', flag: 'py', name: 'Guarani', },
  { key: 'QAR', flag: 'qa', name: 'Qatari Rial', },
  { key: 'RON', flag: 'ro', name: 'Romanian Leu', },
  { key: 'RSD', flag: 'rs', name: 'Serbian Dinar', },
  { key: 'RUB', flag: 'ru', name: 'Russian Ruble', },
  { key: 'RWF', flag: 'rw', name: 'Rwanda Franc', },
  { key: 'SAR', flag: 'sa', name: 'Saudi Riyal', },
  { key: 'SBD', flag: 'sb', name: 'Solomon Islands Dollar', },
  { key: 'SCR', flag: 'sc', name: 'Seychelles Rupee', },
  { key: 'SDG', flag: 'sd', name: 'Sudanese Pound', },
  { key: 'SEK', flag: 'se', name: 'Swedish Krona', },
  { key: 'SGD', flag: 'sg', name: 'Singapore Dollar', },
  { key: 'SHP', flag: 'sh', name: 'Saint Helena Pound', },
  { key: 'SLE', flag: 'sl', name: 'Leone', },
  { key: 'SOS', flag: 'so', name: 'Somali Shilling', },
  { key: 'SRD', flag: 'sr', name: 'Surinam Dollar', },
  { key: 'SSP', flag: 'ss', name: 'South Sudanese Pound', },
  { key: 'STN', flag: 'st', name: 'Dobra', },
  { key: 'SVC', flag: 'sv', name: 'El Salvador Colon', },
  { key: 'SYP', flag: 'sy', name: 'Syrian Pound', },
  { key: 'SZL', flag: 'sz', name: 'Lilangeni', },
  { key: 'THB', flag: 'th', name: 'Baht', },
  { key: 'TJS', flag: 'tj', name: 'Somoni', },
  { key: 'TMT', flag: 'tm', name: 'Turkmenistan New Manat', },
  { key: 'TND', flag: 'tn', name: 'Tunisian Dinar', },
  { key: 'TOP', flag: 'to', name: 'Pa’anga', },
  { key: 'TRY', flag: 'tr', name: 'Turkish Lira', },
  { key: 'TTD', flag: 'tt', name: 'Trinidad and Tobago Dollar', },
  { key: 'TWD', flag: 'tw', name: 'New Taiwan Dollar', },
  { key: 'TZS', flag: 'tz', name: 'Tanzanian Shilling', },
  { key: 'UAH', flag: 'ua', name: 'Hryvnia', },
  { key: 'UGX', flag: 'ug', name: 'Uganda Shilling', },
  { key: 'USD', flag: 'us', name: 'US Dollar', },
  { key: 'UYU', flag: 'uy', name: 'Peso Uruguayo', },
  { key: 'UZS', flag: 'uz', name: 'Uzbekistan Sum', },
  { key: 'VND', flag: 'vn', name: 'Dong', },
  { key: 'VUV', flag: 'vu', name: 'Vatu', },
  { key: 'WST', flag: 'ws', name: 'Tala', },
  { key: 'XAF', flag: 'cm', name: 'CFA Franc BEAC', },
  { key: 'XCD', flag: 'gd', name: 'East Caribbean Dollar', },
  { key: 'XCG', flag: 'cw', name: 'Caribbean Guilder', },
  { key: 'XOF', flag: 'ml', name: 'CFA Franc BCEAO', },
  { key: 'ZAR', flag: 'za', name: 'Rand', },
  { key: 'ZMW', flag: 'zm', name: 'Zambian Kwacha', },
  { key: 'ZWL', flag: 'zw', name: 'Zimbabwe Dollar', },
]