const CURRENCIES_LIST = [
  { key: 'AED', flag: 'ae', icon: '', name: 'United Arab Emirates Dirham', },
  { key: 'AFN', flag: 'af', icon: '؋', name: 'Afghan Afghani', },
  { key: 'ALL', flag: 'al', icon: 'fa-solid fa-dollar-sign', name: 'Albanian Lek', },
  { key: 'AMD', flag: 'am', icon: 'Դ', name: 'Armenian Dram', },
  { key: 'AOA', flag: 'ao', icon: 'fa-solid fa-dollar-sign', name: 'Angolan Kwanza', },
  { key: 'ARS', flag: 'ar', icon: 'fa-solid fa-dollar-sign', name: 'Argentine Peso', },
  { key: 'AUD', flag: 'au', icon: 'fa-solid fa-dollar-sign', name: 'Australian Dollar', },
  { key: 'AWG', flag: 'aw', icon: 'fa-solid fa-florin-sign', name: 'Aruban Florin', },
  { key: 'AZN', flag: 'az', icon: 'fa-solid fa-manat-sign', name: 'Azerbaijanian Manat', },
  { key: 'BAM', flag: 'ba', icon: 'fa-solid fa-dollar-sign', name: 'Bosnia-Herzegovina Convertible Marka', },
  { key: 'BBD', flag: 'bb', icon: 'fa-solid fa-dollar-sign', name: 'Barbados Dollar', },
  { key: 'BDT', flag: 'bd', icon: '৳', name: 'Bangladeshi Taka', },
  { key: 'BHD', flag: 'bh', icon: 'fa-solid fa-dollar-sign', name: 'Bahraini Dinar', },
  { key: 'BIF', flag: 'bi', icon: 'fa-solid fa-dollar-sign', name: 'Burundi Franc', },
  { key: 'BMD', flag: 'bm', icon: 'fa-solid fa-dollar-sign', name: 'Bermudian Dollar', },
  { key: 'BND', flag: 'bn', icon: 'fa-solid fa-dollar-sign', name: 'Brunei Dollar', },
  { key: 'BOB', flag: 'bo', icon: 'fa-solid fa-dollar-sign', name: 'Bolivian Boliviano', },
  { key: 'BRL', flag: 'br', icon: 'fa-solid fa-brazilian-real-sign', name: 'Brazilian Real', },
  { key: 'BSD', flag: 'bs', icon: 'fa-solid fa-dollar-sign', name: 'Bahamian Dollar', },
  { key: 'BTN', flag: 'bt', icon: 'fa-solid fa-dollar-sign', name: 'Bhutanese Ngultrum', },
  { key: 'BWP', flag: 'bw', icon: 'fa-solid fa-dollar-sign', name: 'Botswana Pula', },
  { key: 'BYN', flag: 'by', icon: '', name: 'Belarussian Ruble', },
  { key: 'BZD', flag: 'bz', icon: 'fa-solid fa-dollar-sign', name: 'Belize Dollar', },
  { key: 'CAD', flag: 'ca', icon: 'fa-solid fa-dollar-sign', name: 'Canadian Dollar', },
  { key: 'CDF', flag: 'cd', icon: 'fa-solid fa-dollar-sign', name: 'Congolese Franc', },
  { key: 'CHF', flag: 'ch', icon: 'fa-solid fa-dollar-sign', name: 'Swiss Franc', },
  { key: 'CLF', flag: 'cl', icon: 'fa-solid fa-dollar-sign', name: 'Unidad de Fomento', },
  { key: 'CLP', flag: 'cl', icon: 'fa-solid fa-dollar-sign', name: 'Chilean Peso', },
  { key: 'CNY', flag: 'cn', icon: 'fa-solid fa-yen-sign', name: 'Yuan Renminbi', },
  { key: 'COP', flag: 'co', icon: 'fa-solid fa-dollar-sign', name: 'Colombian Peso', },
  { key: 'CRC', flag: 'cr', icon: 'fa-solid fa-colon-sign', name: 'Costa Rican Colon', },
  { key: 'CUC', flag: 'cu', icon: 'fa-solid fa-dollar-sign', name: 'Cuban Peso Convertible', },
  { key: 'CUP', flag: 'cu', icon: 'fa-solid fa-dollar-sign', name: 'Cuban Peso', },
  { key: 'CVE', flag: 'cv', icon: 'fa-solid fa-dollar-sign', name: 'Cabo Verde Escudo', },
  { key: 'CZK', flag: 'cz', icon: 'fa-solid fa-dollar-sign', name: 'Czech Koruna', },
  { key: 'DJF', flag: 'dj', icon: 'fa-solid fa-dollar-sign', name: 'Djibouti Franc', },
  { key: 'DKK', flag: 'dk', icon: 'fa-solid fa-dollar-sign', name: 'Danish Krone', },
  { key: 'DOP', flag: 'do', icon: 'fa-solid fa-dollar-sign', name: 'Dominican Peso', },
  { key: 'DZD', flag: 'dz', icon: 'fa-solid fa-dollar-sign', name: 'Algerian Dinar', },
  { key: 'EGP', flag: 'eg', icon: 'fa-solid fa-sterling-sign', name: 'Egyptian Pound', },
  { key: 'ERN', flag: 'er', icon: 'fa-solid fa-dollar-sign', name: 'Eritrean Nakfa', },
  { key: 'ETB', flag: 'et', icon: 'fa-solid fa-dollar-sign', name: 'Ethiopian Birr', },
  { key: 'EUR', flag: 'eu', icon: 'fa-solid fa-euro-sign', name: 'Euro', },
  { key: 'FJD', flag: 'fj', icon: 'fa-solid fa-dollar-sign', name: 'Fiji Dollar', },
  { key: 'FKP', flag: 'fk', icon: 'fa-solid fa-sterling-sign', name: 'Falkland Islands Pound', },
  { key: 'GBP', flag: 'gb', icon: 'fa-solid fa-sterling-sign', name: 'Pound Sterling', },
  { key: 'GEL', flag: 'ge', icon: 'fa-solid fa-lari-sign', name: 'Georgian Lari', },
  { key: 'GHS', flag: 'gh', icon: 'fa-solid fa-cedi-sign', name: 'Ghana Cedi', },
  { key: 'GIP', flag: 'gi', icon: 'fa-solid fa-sterling-sign', name: 'Gibraltar Pound', },
  { key: 'GMD', flag: 'gm', icon: 'fa-solid fa-dollar-sign', name: 'Gambian Dalasi', },
  { key: 'GNF', flag: 'gn', icon: 'fa-solid fa-dollar-sign', name: 'Guinea Franc', },
  { key: 'GTQ', flag: 'gt', icon: 'fa-solid fa-dollar-sign', name: 'Quetzal', },
  { key: 'GYD', flag: 'gy', icon: 'fa-solid fa-dollar-sign', name: 'Guyana Dollar', },
  { key: 'HKD', flag: 'hk', icon: 'fa-solid fa-dollar-sign', name: 'Hong Kong Dollar', },
  { key: 'HNL', flag: 'hn', icon: 'fa-solid fa-dollar-sign', name: 'Honduran Lempira', },
  { key: 'HTG', flag: 'ht', icon: 'fa-solid fa-dollar-sign', name: 'Haitian Gourde', },
  { key: 'HUF', flag: 'hu', icon: 'fa-solid fa-dollar-sign', name: 'Hungarian Forint', },
  { key: 'IDR', flag: 'id', icon: 'fa-solid fa-rupiah-sign', name: 'Indonesian Rupiah', },
  { key: 'ILS', flag: 'il', icon: '₪', name: 'New Israeli Sheqel', },
  { key: 'INR', flag: 'in', icon: 'fa-solid fa-indian-rupee-sign', name: 'Indian Rupee', },
  { key: 'IQD', flag: 'iq', icon: 'fa-solid fa-dollar-sign', name: 'Iraqi Dinar', },
  { key: 'IRR', flag: 'ir', icon: 'fa-solid fa-dollar-sign', name: 'Iranian Rial', },
  { key: 'ISK', flag: 'is', icon: 'fa-solid fa-dollar-sign', name: 'Iceland Krona', },
  { key: 'JMD', flag: 'jm', icon: 'fa-solid fa-dollar-sign', name: 'Jamaican Dollar', },
  { key: 'JOD', flag: 'jo', icon: 'fa-solid fa-dollar-sign', name: 'Jordanian Dinar', },
  { key: 'JPY', flag: 'jp', icon: 'fa-solid fa-yen-sign', name: 'Japanese Yen', },
  { key: 'KES', flag: 'ke', icon: 'fa-solid fa-dollar-sign', name: 'Kenyan Shilling', },
  { key: 'KGS', flag: 'kg', icon: '', name: 'Kyrgyz Som', },
  { key: 'KHR', flag: 'kh', icon: 'fa-solid fa-dollar-sign', name: 'Cambodian Riel', },
  { key: 'KMF', flag: 'km', icon: 'fa-solid fa-dollar-sign', name: 'Comoro Franc', },
  { key: 'KPW', flag: 'kp', icon: 'fa-solid fa-won-sign', name: 'North Korean Won', },
  { key: 'KRW', flag: 'kr', icon: 'fa-solid fa-won-sign', name: 'South Korean Won', },
  { key: 'KWD', flag: 'kw', icon: 'fa-solid fa-dollar-sign', name: 'Kuwaiti Dinar', },
  { key: 'KYD', flag: 'ky', icon: 'fa-solid fa-dollar-sign', name: 'Cayman Islands Dollar', },
  { key: 'KZT', flag: 'kz', icon: 'fa-solid fa-tenge-sign', name: 'Kazakhstani Tenge', },
  { key: 'LAK', flag: 'la', icon: 'fa-solid fa-kip-sign', name: 'Laotian Kip', },
  { key: 'LBP', flag: 'lb', icon: 'fa-solid fa-sterling-sign', name: 'Lebanese Pound', },
  { key: 'LKR', flag: 'lk', icon: 'fa-solid fa-rupee-sign', name: 'Sri Lanka Rupee', },
  { key: 'LRD', flag: 'lr', icon: 'fa-solid fa-dollar-sign', name: 'Liberian Dollar', },
  { key: 'LSL', flag: 'ls', icon: 'fa-solid fa-dollar-sign', name: 'Lesotho Loti', },
  { key: 'LYD', flag: 'ly', icon: 'fa-solid fa-dollar-sign', name: 'Libyan Dinar', },
  { key: 'MAD', flag: 'ma', icon: 'fa-solid fa-dollar-sign', name: 'Moroccan Dirham', },
  { key: 'MDL', flag: 'md', icon: 'fa-solid fa-dollar-sign', name: 'Moldovan Leu', },
  { key: 'MGA', flag: 'mg', icon: 'fa-solid fa-dollar-sign', name: 'Malagasy Ariary', },
  { key: 'MKD', flag: 'mk', icon: 'fa-solid fa-dollar-sign', name: 'Macedonian Denar', },
  { key: 'MMK', flag: 'mm', icon: 'fa-solid fa-dollar-sign', name: 'Myanmar Kyat', },
  { key: 'MNT', flag: 'mn', icon: '₮', name: 'Mongolian Tugrik', },
  { key: 'MOP', flag: 'mo', icon: 'fa-solid fa-dollar-sign', name: 'Macanese Pataca', },
  { key: 'MRU', flag: 'mr', icon: 'fa-solid fa-dollar-sign', name: 'Ouguiya', },
  { key: 'MUR', flag: 'mu', icon: 'fa-solid fa-Rupee-sign', name: 'Mauritius Rupee', },
  { key: 'MVR', flag: 'mv', icon: 'fa-solid fa-dollar-sign', name: 'Mauritanian Rufiyaa', },
  { key: 'MWK', flag: 'mw', icon: 'fa-solid fa-dollar-sign', name: 'Malawian Kwacha', },
  { key: 'MXN', flag: 'mx', icon: 'fa-solid fa-dollar-sign', name: 'Mexican Peso', },
  { key: 'MYR', flag: 'my', icon: 'fa-solid fa-dollar-sign', name: 'Malaysian Ringgit', },
  { key: 'MZN', flag: 'mz', icon: 'fa-solid fa-dollar-sign', name: 'Mozambique Metical', },
  { key: 'NAD', flag: 'na', icon: 'fa-solid fa-dollar-sign', name: 'Namibia Dollar', },
  { key: 'NGN', flag: 'ng', icon: 'fa-solid fa-naira-sign', name: 'Nigerian Naira', },
  { key: 'NIO', flag: 'ni', icon: 'fa-solid fa-dollar-sign', name: 'Cordoba Oro', },
  { key: 'NOK', flag: 'no', icon: 'fa-solid fa-dollar-sign', name: 'Norwegian Krone', },
  { key: 'NPR', flag: 'np', icon: 'रु', name: 'Nepalese Rupee', },
  { key: 'NZD', flag: 'nz', icon: 'fa-solid fa-dollar-sign', name: 'New Zealand Dollar', },
  { key: 'OMR', flag: 'om', icon: 'fa-solid fa-dollar-sign', name: 'Rial Omani', },
  { key: 'PAB', flag: 'pa', icon: 'fa-solid fa-baht-sign', name: 'Panamanian Balboa', },
  { key: 'PEN', flag: 'pe', icon: 'fa-solid fa-dollar-sign', name: 'Nuevo Sol', },
  { key: 'PGK', flag: 'pg', icon: 'fa-solid fa-dollar-sign', name: 'Papua New Guinean Kina', },
  { key: 'PHP', flag: 'ph', icon: 'fa-solid fa-peso-sign', name: 'Philippine Peso', },
  { key: 'PKR', flag: 'pk', icon: 'fa-solid fa-rupee-sign', name: 'Pakistan Rupee', },
  { key: 'PLN', flag: 'pl', icon: 'fa-solid fa-dollar-sign', name: 'Polish Zloty', },
  { key: 'PYG', flag: 'py', icon: 'fa-solid fa-guarani-sign', name: 'Paraguayan Guarani', },
  { key: 'QAR', flag: 'qa', icon: 'fa-solid fa-dollar-sign', name: 'Qatari Rial', },
  { key: 'RON', flag: 'ro', icon: 'fa-solid fa-dollar-sign', name: 'Romanian Leu', },
  { key: 'RSD', flag: 'rs', icon: 'fa-solid fa-dollar-sign', name: 'Serbian Dinar', },
  { key: 'RUB', flag: 'ru', icon: 'fa-solid fa-ruble-sign', name: 'Russian Ruble', },
  { key: 'RWF', flag: 'rw', icon: 'fa-solid fa-dollar-sign', name: 'Rwanda Franc', },
  { key: 'SAR', flag: 'sa', icon: '⃁', name: 'Saudi Riyal', },
  { key: 'SBD', flag: 'sb', icon: 'fa-solid fa-dollar-sign', name: 'Solomon Islands Dollar', },
  { key: 'SCR', flag: 'sc', icon: 'fa-solid fa-rupee-sign', name: 'Seychelles Rupee', },
  { key: 'SDG', flag: 'sd', icon: 'fa-solid fa-dollar-sign', name: 'Sudanese Pound', },
  { key: 'SEK', flag: 'se', icon: 'fa-solid fa-dollar-sign', name: 'Swedish Krona', },
  { key: 'SGD', flag: 'sg', icon: 'fa-solid fa-dollar-sign', name: 'Singapore Dollar', },
  { key: 'SHP', flag: 'sh', icon: 'fa-solid fa-sterling-sign', name: 'Saint Helena Pound', },
  { key: 'SLE', flag: 'sl', icon: 'fa-solid fa-dollar-sign', name: 'Sierra Leonean Leone', },
  { key: 'SOS', flag: 'so', icon: 'fa-solid fa-dollar-sign', name: 'Somali Shilling', },
  { key: 'SRD', flag: 'sr', icon: 'fa-solid fa-dollar-sign', name: 'Surinam Dollar', },
  { key: 'SSP', flag: 'ss', icon: 'fa-solid fa-sterling-sign', name: 'South Sudanese Pound', },
  { key: 'STN', flag: 'st', icon: 'fa-solid fa-dollar-sign', name: 'São Tomé and Príncipe Dobra', },
  { key: 'SVC', flag: 'sv', icon: 'fa-solid fa-colon-sign', name: 'El Salvador Colon', },
  { key: 'SYP', flag: 'sy', icon: 'fa-solid fa-sterling-sign', name: 'Syrian Pound', },
  { key: 'SZL', flag: 'sz', icon: 'fa-solid fa-dollar-sign', name: 'Swazi Lilangeni', },
  { key: 'THB', flag: 'th', icon: 'fa-solid fa-baht-sign', name: 'Thai Baht', },
  { key: 'TJS', flag: 'tj', icon: 'fa-solid fa-dollar-sign', name: 'Tajikistani Somoni', },
  { key: 'TMT', flag: 'tm', icon: 'fa-solid fa-dollar-sign', name: 'Turkmenistan New Manat', },
  { key: 'TND', flag: 'tn', icon: 'fa-solid fa-dollar-sign', name: 'Tunisian Dinar', },
  { key: 'TOP', flag: 'to', icon: 'fa-solid fa-dollar-sign', name: 'Tongan Pa’anga', },
  { key: 'TRY', flag: 'tr', icon: 'fa-solid fa-turkish-lira-sign', name: 'Turkish Lira', },
  { key: 'TTD', flag: 'tt', icon: 'fa-solid fa-dollar-sign', name: 'Trinidad and Tobago Dollar', },
  { key: 'TWD', flag: 'tw', icon: 'fa-solid fa-dollar-sign', name: 'New Taiwan Dollar', },
  { key: 'TZS', flag: 'tz', icon: 'fa-solid fa-dollar-sign', name: 'Tanzanian Shilling', },
  { key: 'UAH', flag: 'ua', icon: 'fa-solid fa-hryvnia-sign', name: 'Ukrainian Hryvnia', },
  { key: 'UGX', flag: 'ug', icon: 'fa-solid fa-dollar-sign', name: 'Uganda Shilling', },
  { key: 'USD', flag: 'us', icon: 'fa-solid fa-dollar-sign', name: 'United States Dollar', },
  { key: 'UYU', flag: 'uy', icon: 'fa-solid fa-dollar-sign', name: 'Peso Uruguayo', },
  { key: 'UZS', flag: 'uz', icon: 'fa-solid fa-dollar-sign', name: 'Uzbekistan Sum', },
  { key: 'VND', flag: 'vn', icon: 'fa-solid fa-dong-sign', name: 'Viet Nam Dong', },
  { key: 'VUV', flag: 'vu', icon: 'fa-solid fa-dollar-sign', name: 'Vanuatu Vatu', },
  { key: 'WST', flag: 'ws', icon: 'fa-solid fa-dollar-sign', name: 'Samoan Tala', },
  { key: 'XAF', flag: 'cm', icon: 'fa-solid fa-dollar-sign', name: 'Central African CFA Franc', },
  { key: 'XCD', flag: 'gd', icon: 'fa-solid fa-dollar-sign', name: 'East Caribbean Dollar', },
  { key: 'XCG', flag: 'cw', icon: 'fa-solid fa-dollar-sign', name: 'Caribbean Guilder', },
  { key: 'XOF', flag: 'ml', icon: 'fa-solid fa-dollar-sign', name: 'West African CFA Franc', },
  { key: 'ZAR', flag: 'za', icon: 'fa-solid fa-dollar-sign', name: 'South African Rand', },
  { key: 'ZMW', flag: 'zm', icon: 'fa-solid fa-dollar-sign', name: 'Zambian Kwacha', },
  { key: 'ZWL', flag: 'zw', icon: 'fa-solid fa-dollar-sign', name: 'Zimbabwe Dollar', },
]